# environment variables
environment: GO_ENV     # defaults to development
config_file: GO_CONFIG  # defaults to ./config/config.yaml
shard: GO_SHARD

development:
    port: 9999
    log_file: ./log/redismq.log
    redis:
        db: 9

gotesting:
    log_file: ./log/redismq.log
    redis:
        db: 9

travis:
    log_file: ../test/log/redismq.log
    redis:
        db: 1
        port: 6379

testing:
    log_file: ./log/redismq.log
    redis:
        port: 63791

staging:
    log_file: /var/log/redismq/redismq.log

production:
    log_file: /var/log/redismq/redismq.log
    redis:
        port: 63791

defaults:
    log_file: ./log/redismq.log
    redis:
        host: localhost
        port: 6379
        db: 9
